-- MySQL Script generated by MySQL Workbench
-- Sat Jul 23 20:39:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shop` DEFAULT CHARACTER SET utf8 ;
USE `db_shop` ;

-- -----------------------------------------------------
-- Table `db_shop`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shop`.`product_image` (
  `id_img` INT NOT NULL,
  `name_group_img` VARCHAR(40) NOT NULL,
  `main_alt` VARCHAR(40) NOT NULL,
  `main_url` VARCHAR(80) NOT NULL,
  `img01_alt` VARCHAR(40) NULL,
  `img01_url` VARCHAR(80) NULL,
  `img02_alt` VARCHAR(40) NULL,
  `img02_url` VARCHAR(80) NULL,
  `img03_alt` VARCHAR(40) NULL,
  `img03_url` VARCHAR(80) NULL,
  PRIMARY KEY (`id_img`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shop`.`product` (
  `id_product` INT NOT NULL,
  `product_name` VARCHAR(50) NULL,
  `quantity` INT NULL,
  `current_price` INT NULL,
  `old_price` INT NULL,
  `promo_price` INT NULL,
  `description` TEXT NULL,
  `name_group_img` INT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `name_group_image_idx` (`name_group_img` ASC) VISIBLE,
  CONSTRAINT `name_group_image`
    FOREIGN KEY (`name_group_img`)
    REFERENCES `db_shop`.`product_image` (`id_img`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shop`.`catalog` (
  `id_catalog` INT NOT NULL,
  `catalog_name` VARCHAR(45) NULL,
  `catalog_description` TEXT NULL,
  PRIMARY KEY (`id_catalog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`catalog_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shop`.`catalog_has_product` (
  `catalog_id_catalog` INT NOT NULL,
  `product_id_product` INT NOT NULL,
  PRIMARY KEY (`catalog_id_catalog`, `product_id_product`),
  INDEX `fk_catalog_has_product_product1_idx` (`product_id_product` ASC) VISIBLE,
  INDEX `fk_catalog_has_product_catalog_idx` (`catalog_id_catalog` ASC) VISIBLE,
  CONSTRAINT `fk_catalog_has_product_catalog`
    FOREIGN KEY (`catalog_id_catalog`)
    REFERENCES `db_shop`.`catalog` (`id_catalog`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_catalog_has_product_product1`
    FOREIGN KEY (`product_id_product`)
    REFERENCES `db_shop`.`product` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
